import { Router } from "express";
import { dashboard, exportParticipants, login, searchParticipants } from "../controllers/adminController.js";
import { adminAuth } from "../middleware/adminAuth.js";
const router = Router();
router.post("/login", login);
router.use(adminAuth);
router.get("/dashboard", dashboard);
router.get("/participants", searchParticipants);
router.get("/export", exportParticipants);
export default router;
