import "dotenv/config";
import path from "path";
import { fileURLToPath } from "url";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import morgan from "morgan";
import { connectDatabase } from "./config/db.js";
import { sanitizeBody } from "./middleware/sanitize.js";
import { errorHandler } from "./middleware/errorHandler.js";
import participantRoutes from "./routes/participantRoutes.js";
import quizRoutes from "./routes/quizRoutes.js";
import scenarioRoutes from "./routes/scenarioRoutes.js";
import leaderboardRoutes from "./routes/leaderboardRoutes.js";
import adminRoutes from "./routes/adminRoutes.js";

const app = express();
const frontend = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "frontend");
app.use(helmet({ contentSecurityPolicy: false }));
app.use(cors({ origin: process.env.CLIENT_ORIGIN?.split(",") || true }));
app.use(morgan(process.env.NODE_ENV === "production" ? "combined" : "dev"));
app.use(express.json({ limit: "20kb" }));
app.use(sanitizeBody);
app.use("/api", participantRoutes);
app.use("/api", quizRoutes);
app.use("/api", scenarioRoutes);
app.use("/api", leaderboardRoutes);
app.use("/api/admin", adminRoutes);
app.use(express.static(frontend));
app.use(errorHandler);

connectDatabase().then(() => app.listen(process.env.PORT || 5000, () => console.log(`CyberSafe server running on port ${process.env.PORT || 5000}`))).catch((error) => { console.error("Server startup failed:", error.message); process.exit(1); });
